name: Update Profile Readme

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install github-readme-contribution-stats

      - name: Generate Contribution Graph SVG
        run: npx github-readme-contribution-stats --profile <YOUR_GITHUB_USERNAME> --svg > contribution_graph.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Snake Animation to SVG
        run: |
          # Add your SVG manipulation code here to add the snake animation
          # Replace the content inside the << >> with your actual SVG manipulation code

          # Example SVG Manipulation Code:
          cat contribution_graph.svg | sed -e '
            # Find the opening <svg> tag and add a viewbox attribute if not present
            /<svg/ { /viewBox/! s/<svg /<svg viewBox="0 0 800 300" / }

            # Append the snake line to the SVG
            /<\/svg>/ i <line id="snake" x1="0" y1="150" x2="50" y2="150" style="stroke: red; stroke-width: 3;" /> 
          ' > contribution_graph_with_snake.svg
      - name: Commit and Push Changes
        run: |
          git config --global user.email "<YOUR_GITHUB_EMAIL>"
          git config --global user.name "<YOUR_GITHUB_USERNAME>"
          git add contribution_graph_with_snake.svg
          git commit -m "Update Contribution Graph with Snake Animation"
          git push origin main
